<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>Web.TestData</RootNamespace>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="../../src/Web/Web.csproj"/>
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Web.Tests"/>
		<InternalsVisibleTo Include="Web.Integration.Tests"/>
	</ItemGroup>

</Project>
