<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<IsAspireSharedProject>false</IsAspireSharedProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MongoDB.Bson"/>
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Architecture.Tests" />
		<InternalsVisibleTo Include="Domain.Tests" />
		<InternalsVisibleTo Include="Web.Tests" />
		<InternalsVisibleTo Include="Web.UI.Tests" />
	</ItemGroup>

</Project>
