<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<OutputType>Exe</OutputType>
		<RootNamespace>Web.E2E.Tests</RootNamespace>
		<UserSecretsId>94491f6e-auth0-values-3ff40da38702</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App"/>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FluentAssertions"/>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
		<PackageReference Include="Microsoft.Playwright"/>
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage"/>
		<PackageReference Include="xunit.v3.mtp-v2"/>
	</ItemGroup>

	<ItemGroup>
		<Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest"/>
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit"/>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../../src/Web/Web.csproj"/>
	</ItemGroup>

</Project>
