// ============================================
// Copyright (c) 2026. All rights reserved.
// File Name :     ArticleImage.cs
// Company :       mpaulosky
// Author :        Teqslamer
// Solution Name : Articles
// Project Name :  Web
// =============================================

using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace Web.Components.Features.Articles.Models;

/// <summary>
///   Represents one image referenced inside an article's content, tracked as structured data
///   alongside the markdown link it corresponds to. See ADR-0003.
/// </summary>
[Serializable]
public sealed class ArticleImage
{
	/// <summary>
	///   Initializes a new empty article image snapshot for serialization and test data generation.
	/// </summary>
	public ArticleImage() : this(string.Empty, string.Empty, 0, string.Empty, string.Empty, DateTime.UnixEpoch)
	{
	}

	/// <summary>
	///   Initializes a new instance of the <see cref="ArticleImage" /> class.
	/// </summary>
	/// <param name="fileName">The stored file name, as generated by the upload pipeline.</param>
	/// <param name="url">The URL the article's content links to (e.g. <c>/uploads/{fileName}</c>).</param>
	/// <param name="sizeInBytes">The file size in bytes.</param>
	/// <param name="mimeType">The file's content type.</param>
	/// <param name="altText">The alt text/caption, as written in the markdown image link.</param>
	/// <param name="uploadedAt">The UTC date and time the file was uploaded.</param>
	private ArticleImage(
		string fileName,
		string url,
		long sizeInBytes,
		string mimeType,
		string altText,
		DateTime uploadedAt)
	{
		FileName = fileName;
		Url = url;
		SizeInBytes = sizeInBytes;
		MimeType = mimeType;
		AltText = altText;
		UploadedAt = uploadedAt;
	}

	/// <summary>
	///   Gets or sets the stored file name, as generated by the upload pipeline.
	/// </summary>
	[BsonElement("fileName")]
	[BsonRepresentation(BsonType.String)]
	public string FileName { get; set; }

	/// <summary>
	///   Gets or sets the URL the article's content links to (e.g. <c>/uploads/{fileName}</c>).
	/// </summary>
	[BsonElement("url")]
	[BsonRepresentation(BsonType.String)]
	public string Url { get; set; }

	/// <summary>
	///   Gets or sets the file size in bytes.
	/// </summary>
	[BsonElement("sizeInBytes")]
	public long SizeInBytes { get; set; }

	/// <summary>
	///   Gets or sets the file's content type.
	/// </summary>
	[BsonElement("mimeType")]
	[BsonRepresentation(BsonType.String)]
	public string MimeType { get; set; }

	/// <summary>
	///   Gets or sets the alt text/caption, as written in the markdown image link.
	/// </summary>
	[BsonElement("altText")]
	[BsonRepresentation(BsonType.String)]
	public string AltText { get; set; }

	/// <summary>
	///   Gets or sets the UTC date and time the file was uploaded.
	/// </summary>
	[BsonElement("uploadedAt")]
	[BsonRepresentation(BsonType.DateTime)]
	public DateTime UploadedAt { get; set; }

	/// <summary>
	///   Creates an <see cref="ArticleImage" /> snapshot.
	/// </summary>
	public static ArticleImage Create(
		string fileName,
		string url,
		long sizeInBytes,
		string mimeType,
		string altText,
		DateTime uploadedAt)
	{
		ArgumentException.ThrowIfNullOrWhiteSpace(fileName);
		ArgumentException.ThrowIfNullOrWhiteSpace(url);

		return new ArticleImage(
			fileName.Trim(),
			url.Trim(),
			sizeInBytes,
			mimeType?.Trim() ?? string.Empty,
			altText?.Trim() ?? string.Empty,
			uploadedAt);
	}
}
